# DocFX Filtering Rules
apiRules:
- include: # The namespaces to generate
    uidRegex: ^SpiraTec\.IOSEF\.Runtime
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace
